[window_mode]
width = 1920
height = 1080
borderless = false
fullscreen_type = "True"
vsync = true
min_width = 0
min_height = 0
max_width = 0
max_height = 0

[window_setup]
title = "An easy, good game"
icon = ""
resizable = false
allow_highdpi = true
samples = "One"

[backend]
type = "OpenGL"
major = 3
minor = 2

[camera]
preview_width = 100
preview_height = 100
